### PR TITLE
Enable damaging templating, template eswiki, eswikibooks, etwiki

### PR DESCRIPTION
**Pull request by Ladsgroup**
Bug: T168455

### CODE REVIEW

**Comment by Ladsgroup** [comment]
Diff: https://gist.github.com/Ladsgroup/ad77bf59273263134e4c4dc5a1cc0309#file-damging_batch-patch

**Comment by adamwight** [comment]
The eswiki `revscoring extract` feature lists look wrong.  One set gets the reverted features, another gets the damaging and goodfaith features, but then they get merged together.

**Comment by adamwight** [comment]
eswikibooks trusted groups are missing "autopatrolled".

**Comment by Ladsgroup** [comment]
Regarding revscoring extract, that's a problem in the manual file which this actually fixes because there are two use of revscoring extract, one on "autolabeled" dataset and the other one on "labeled" dataset, the former only needs revert while the latter needs damaging and goodfaith (and not reverted). In reality it's not different because we use the same feature set for all.

**Comment by Ladsgroup** [comment]
Fixed the eswikibooks user groups. Thanks for noticing

**Pull request merged**
