### PR TITLE
Add damaging and goodfaith models for huwiki

### PR DESCRIPTION
**Pull request by tgr**
Also remove reverted and update the list of trusted groups.

Bug: [T185903](https://phabricator.wikimedia.org/T185903)

### CODE REVIEW

**Comment by tgr** [comment]
Not sure what to do with the files in `model_info`. If those are not supposed to be comitted, there should probably be a gitignore rule for them.

**Comment by adamwight** [comment]
> Not sure what to do with the files in model_info. If those are not supposed to be comitted, there should probably be a gitignore rule for them.

These are a new thing, and we do want to commit them.  Going forward, this will give us an easy way to record and review how model health is changing.

**Comment by adamwight** [comment]
The only issue I see with this PR is that the huwiki models need to be rebuilt, because the merge_labels algorithm has changed since these patches were rebased.

**Comment by tgr** [comment]
> These are a new thing, and we do want to commit them.

Added.

> The only issue I see with this PR is that the huwiki models need to be rebuilt, because the merge_labels algorithm has changed since these patches were rebased.

These are the rebuilt models. Is something wrong with them?

**Comment by adamwight** [comment]
> These are the rebuilt models. Is something wrong with them?

Ah, my fault—I looked at the timestamp on the commit, didn't know how else to verify whether they were rebuilt.

**Comment by adamwight** [comment]
Great work, thanks!

**Comment by halfak** [comment]
\o/

**Comment by adamwight** [comment]
I was too quick to merge this, it looks like there's still work to do.  Compare the damaging model_info with https://phabricator.wikimedia.org/P6931 and the good-faith model_info with https://phabricator.wikimedia.org/P6934, you'll see that the models I built were much healthier for some reason.  Assuming this is repeatable, I'll compare our branches.

**Comment by adamwight** [comment]
Here's the missing piece: #153

**Pull request merged**
