### PR TITLE
Rebuild models for revscoring 1.3.15

### PR DESCRIPTION
**Pull request by halfak**

### CODE REVIEW

**Comment by Pix1234** [comment]
please avoid blindly merging.

Zppix
Volunteer developer for WMF
enwp.org/User:Zppix

**Comment by adamwight** [comment]
@Pix1234 
You/we bring up a very good point:  How would we *ever* be able to trust binary models?  We have reasonable guarantees that halfak did create the models on his machine, since I was in IRC with him and git does hashing or something to ensure file contents... but a pickled file can contain all manner of naughty Python things, which could be injected by a compromised build system.  It's an interesting problem!  It would be nice if we could serialize models to a text-only, numeric representation, maybe that's something to look into in the distant future.

**Comment by halfak** [comment]
@adamwight, thank you for explicitly noting what you are and are not blindly trusting here.  This is something we should do more of.

**Pull request merged**
