### PR TITLE
(WIP) Config changes for reverted models.

### PR DESCRIPTION
**Pull request by halfak**

### CODE REVIEW

**Comment by halfak** [comment]
@groceryheist, I'm working on tuning this enwiki model.  Let me know if you have any questions.

**Comment by groceryheist** [comment]
Thanks! So to me it looks like we need to do the following to support in-vivo evaluation. 

- [ ] Create new samples. This should be a large random samples either uniform or stratified by (i.e., editor type, week, namespace, whether they were reverted, other discrete variables). The sample should cover the range from 1 year before ORES was released until 1 year afterward.  
- [ ] Add a feature for whether or not an editor is a newcomer.
- [ ] Generate such datasets for all Wikis (not just those with ORES enabled). We can use auto-generated badwords lists for this. 
- [ ] Fit logistic regression models for each wiki. (Still not sure about this. we might only need 1 big model for all wikis in the end). 

Doing grid search and regularization for these models is fine, but I think we should include "no regularization" as an option in the grid search.  This is a problem since apparently logistic regression in sklearn only provides an option to turn off regularization in version 0.21.2  so we'll need to update that dependency.

**Comment by halfak** [comment]
We already have a feature that measures the seconds_since_registration.  Is that sufficient for "newcomer"?

Why does it have to be a logistic regression again?  It seems like a logistic model doesn't fit nearly as well.

Why would we gather data *after* ORES is deployed?  Surely, our suspicion is the ORES affects reverting behavior.  If we are learning ORES effects as part of the revert prediction model, that would affect our conclusions, wouldn't it?

**Comment by groceryheist** [comment]
We talked offline about this. We need data before and after the deployment because we want to estimate a model that has a coefficient for ores being deployed.  Let's pause on this to see how a somewhat simpler strategy pans out.

**Pull request closed without merging**
