### PR TITLE
Rebuilding models that now use nltk stopwords

### PR DESCRIPTION
**Pull request by Ladsgroup**

### CODE REVIEW

**Comment by halfak** [comment]
I think we should be working with a new version of revscoring -- otherwise the information stored in model_info is confusing.  Sorry to be a pain.  I'll get to work on cutting a new revscoring version in pypi

**Comment by halfak** [comment]
{{done}}

**Comment by Ladsgroup** [comment]
when I rebuilt this model, I installed revscoring from master, isn't it enough?

**Comment by halfak** [comment]
Oh!  One more thing.  Could you add revscoring 2.1.0 to the requirements? :D

**Pull request merged**
