### PR TITLE
Update test_statistics for damaging and goodfaith filtering

### PR DESCRIPTION
**Pull request by stephanebisson**
Update test_statistics to produce thresholds used for damaging and goodfaith filtering.

### CODE REVIEW

**Comment by halfak** [comment]
This looks good.  We'll need to rebuild all of the models to account for these new statistics.  I'll get that started on ores-compute-01 now.  Please do not merge until that is complete.

**Comment by stephanebisson** [comment]
Is the rebuilding of the models finished?

**Comment by halfak** [comment]
Sorry for the delay.  We had a few other things come up.  I'm working on this again.

**Comment by halfak** [comment]
@Ladsgroup this will change the available test statistics for the editquality models, will we need to change anything substantially for the ORES extension when we deploy this?

**Comment by halfak** [comment]
Model building started.  If all goes well, we'll have new models ready by the regularly scheduled hack session tomorrow morning.

**Comment by halfak** [comment]
Quick update: I've rebuilt models from arwiki to ruwiki.  There's only a few more, so I'll definitely be able to merge tomorrow morning.  I'll likely do a deployment to ores.wmflabs.org too.  You'll be able to test against that while we prepare for a deploy to ores.wikimedia.org.

**Comment by Ladsgroup** [comment]
If it's changing the thresholds, yes. We can do it in our deployment window at the same time. I can do it and did once before.

**Comment by halfak** [comment]
BTW, this is now deployed on Wikimedia Labs.  See https://ores.wmflabs.org/v2/scores/?model_info=test_stats

We'll need to wait for a deployment window to deploy to ores.wikimedia.org.

**Pull request merged**
