### PR TITLE
Scale up the number of observations for idwiki to 100k

### PR DESCRIPTION
**Pull request by nikitavbv**
Bug: T147107

### CODE REVIEW

**Comment by halfak** [comment]
Looks good to me.  @Ladsgroup, we might want to rebuild the model from
ores-compute-01.eqiad.wmnet before doing the merge.  I'll get to that in
~12 hours if you don't beat me to it.

**Comment by Ladsgroup** [comment]
@halfak the model is already in the PR. I can rebuild it once it's merged (since it's forked in another repo, not here) Do you mean something like this?

**Comment by halfak** [comment]
What I usually do in this case is follow the "Merging via command line" instructions and add a commit before finishing the merge.

**Comment by halfak** [comment]
I'm running the whole flow on ores-compute-01 right now :)

**Pull request merged**
