### PR TITLE
Add eswikiversity

### PR DESCRIPTION
**Pull request by Ladsgroup**
This has 17k edit for two-year span because anything smaller is not possible

Bug: T209670

### CODE REVIEW

**Comment by halfak** [comment]
Wow!  Sampling at 100%.  What proportion are "reverted_for_damage"?  Is it enough?

**Comment by Ladsgroup** [comment]
> Wow! Sampling at 100%. What proportion are "reverted_for_damage"? Is it enough?

(p3) ladsgroup@stat1007:~/editquality$ grep '"reverted_for_damage": true' datasets/eswikiversity.autolabeled_revisions.17k_2019.json | wc -l
2190

I think that's good. Needs review is 10727 edits though.

**Comment by halfak** [comment]
Wow!  That's actually a really high proportion!  Over 10% of edits are "reverted_for_damage"!  What are the dominant reasons for "needs_review"?  Maybe there are a lot of anons or we're setting the "trusted_edits" too high.  Do we have someone from eswikiversity who could help?

**Comment by halfak** [comment]
Ping @Ladsgroup ^

**Comment by Ladsgroup** [comment]
> What are the dominant reasons for "needs_review"?

ladsgroup@stat1007:~/editquality$ grep '"reverted_for_damage": true' datasets/eswikiversity.autolabeled_revisions.17k_2019.json | jq .autolabel.review_reason | sort | uniq -c
   2190 "reverted edit"

**Comment by halfak** [comment]
OK my conclusion is to add 'autoconfirmed' users to the "trusted_groups" list.  It works.  The "needs_review" is down below 5k.

**Comment by halfak** [comment]
@Nettrom, could you take a look at this?  The gist of the change is that we're looking to add "autoconfirmed" users to the "trusted groups" list.  See https://phabricator.wikimedia.org/T209670 for a discussion with Lsanabria about choosing this low bar.  Note that any edits that are reverted or saved by now-blocked users will be flagged for review even if they were saved by a "trusted" editor.  There's not much to review here -- just configuration changes, so I'm hoping you'll either comment on any typos or weirdness you see there.  Or if you'd like to discuss the autolabeling and "trusted" strategy we came up with, that would be welcome.

**Comment by groceryheist** [comment]
Looks good to me!

**Pull request merged**
