### PR TITLE
Give trusted groups precedence over if it's blocked

### PR DESCRIPTION
**Pull request by Ladsgroup**
See T195701#4412114

Bug: T195701

### CODE REVIEW

**Comment by halfak** [comment]
Looks good to me.  Could you run this on the Wikidata dataset and see if it does what we expect (far fewer "needs_review" edits)?

**Comment by Ladsgroup** [comment]
I tried it and doesn't work for two reasons: 1- Either the user has been stripped from the bot right 2- or They were using semi-automated tools to edit and didn't have bot rights at all. Almost all of blocked users were because of disruptive editing or any other form "sneaky damaging behaviour" that is not our concern. I propose to remove the block part completely.

**Comment by halfak** [comment]
Hmm.. Edits by blocked users in other wikis seems to be good for review.  maybe we can add a flag to make an exception here.  Or we could filter after the fact for the "needs_review" reason "blocked_user"

**Comment by Ladsgroup** [comment]
The latter requires less coding and given the special case we have here, I think it's good to do it. Do I have the greenlight?

**Comment by halfak** [comment]
+1 go for it :)  I'll review :D

**Comment by Ladsgroup** [comment]
Done in #166

**Pull request closed without merging**
