### PR TITLE
Template jawiki, kowiki, tawiki, ukwiki

### PR DESCRIPTION
**Pull request by Ladsgroup**
This is the all I can do with this way of automation, will improve and template more

Bug: T168455

### CODE REVIEW

**Comment by Ladsgroup** [comment]
https://gist.github.com/Ladsgroup/ad77bf59273263134e4c4dc5a1cc0309

**Comment by adamwight** [comment]
One harmless thing mentioned in a gist comment.

**Comment by Ladsgroup** [comment]
Noted and handled :P

**Comment by adamwight** [comment]
💯

**Pull request merged**
