### PR TITLE
Rebuild models with revscoring 2.3.3

### PR DESCRIPTION
**Pull request by Ladsgroup**

### CODE REVIEW

**Comment by halfak** [comment]
model_info/cswiki.damaging.md sees a big decrease in fitness and a reduction in total observations from 19951 to 17854.  It looks like something went wrong there.

**Comment by halfak** [comment]
Same story for model_info/hewiki.damaging.md

**Comment by halfak** [comment]
I'm also seeing a lot of changes to "reverted" proportions.  It looks like fewer reverted_for_damage revisions than before.  Often the proportion is more than cut in half!  E.g. for idwiki's reverted model, I see:

	Statistics:		                                  Statistics:
	counts (n=98654):		                          counts (n=98615):
		label        n         ~True    ~False			label        n         ~True    ~False
		-------  -----  ---  -------  --------			-------  -----  ---  -------  --------
		True      2580  -->     1680       900			True       955  -->      395       560
		False    96074  -->     5692     90382			False    97660  -->     1685     95975

**Comment by halfak** [comment]
I confirmed that cswiki's disparity in observations is actually due to us fixing a bug in our process for generating training data.  

When I run the autolabeler on fiwiki's dataset as intended, I can confirm the drop in "reverted_for_damage" observations. 

```
$ cat datasets/idwiki.autolabeled_revisions.100k_2016.json | json2tsv reverted_for_damage | sort | uniq -c 
  97660 False
    955 True
```

**Comment by halfak** [comment]
When we remove the revert-window and revert-radius limits from idwiki's autolabel call, I get something that reflects what we have seen in the past: 

```
$ cat datasets/idwiki.autolabeled_revisions.100k_2016.json | json2tsv reverted_for_damage | sort | uniq -c
   95934 False
   2681 True
```

I think that we likely normalized on the use of a small revert radius when we started templating all of the make file and I never updated the labeled datasets because I thought there was no good reason to.  I think that we're going to want to remove the default of revert-window of 48 hours.  I think the revert radius of 3 is probably also a little too strict, but I want to run a test to be sure.

**Comment by Ladsgroup** [comment]
Fixing it is outside of scope of this PR IMO

**Comment by halfak** [comment]
This is what I get after keeping the 3 revert radius but dropping the window.  Let's see what happens if I extend the radius to 5. 

```
$ cat datasets/idwiki.autolabeled_revisions.100k_2016.json | json2tsv reverted_for_damage | sort | uniq -c
   96900 False
   1715 True
```

**Comment by halfak** [comment]
This is with no window and revert-radius = 5.  I think it's pretty good.

```
cat datasets/idwiki.autolabeled_revisions.100k_2016.json | json2tsv reverted_for_damage | sort | uniq -c
   96582 False
   2033 True
```

**Comment by halfak** [comment]
https://github.com/wikimedia/editquality/blob/1a1cbada398e78fc213e96ec8699850207068d3a/templates/Makefile.j2#L44 

It looks like we have hard-coded these limits for all models and we have left it unconfigurable.  This regressions is primarily due to this issue.  I think we need to address it before deploying these models.  It should be relatively straightforward to change in the template.  The hard part will be determining which wikis get which parameters.  I would set the default to be no window and revert-radius=5.  Then for big wikis where we believe quality control to be consistent and quick (enwiki, dewiki, jawiki, itwiki, frwiki, etc.), we can set the window to 48 hours in the config.   I'll make a task.

**Comment by halfak** [comment]
See https://phabricator.wikimedia.org/T215671

**Pull request merged**
